apiVersion: v1
kind: Service
metadata:
  name: deposit-service
  labels:
    app: deposit-service
spec:
  type: ClusterIP
  ports:
    - port: 8881
      name: http
  selector:
    app: deposit-service