apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  type: ClusterIP
  ports:
    - port: 8880
      name: http
  selector:
    app: account-service